server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

        # ✅ THÊM ROUTE CHO UPLOADS - PHẢI ĐẶT TRƯỚC ROUTE PRODUCT SERVICE
      routes:
        - id: product-uploads
          uri: lb://product-service
          predicates:
            - Path=/uploads/products/**
          filters:
            - RemoveRequestHeader=Cookie  # Bỏ Cookie để tránh CORS issues

        # PRODUCT SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,
                  /api/categories/**,
                  /api/suppliers/**

        # INVENTORY SERVICE
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/stores/**,
                   /api/imports/**,
                   /api/exports/**,
                   /api/stocks/**

        # ORDER SERVICE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/customers/**,/api/orders/**

        # PROMOTION SERVICE
        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=/api/vouchers/**

        # SETTING SERVICE
        - id: settings-cms-service
          uri: lb://settings-cms-service
          predicates:
            - Path=/api/settings/**, /api/post-categories/**, /api/posts/**

        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka